## Rookies

This notebook combines the receiving dataset with the draft and debut dataset in order to get average stats of Rookies based on what round they were drafted in.

In [2]:
import pandas as pd
import numpy as np

In [3]:
def rookies(year):
    df = pd.read_csv(('../data/receiving/' + str(year) + '_receiving_basic_original.csv'))
    draft = pd.read_csv('../data/draft_final.csv')
    debut = pd.read_csv('../data/debut_final.csv')

    draft.rename(columns = {'Pos': 'DPos'}, inplace = True)

    df = df.merge(draft, how = 'left', on = 'Player-additional')
    df = df.merge(debut, how = 'left', on = 'Player-additional')

    df.drop(columns = ['Rk', 'Pos', 'DPos', 'DraftYear'], inplace = True)

    df['Rnd'].fillna(8, inplace = True)
    df['Pick'].fillna(260, inplace = True)
    
    df = df[df['RookieYear'] == year]

    return df

In [4]:
df1 = rookies(2021)
df2 = rookies(2020)
df3 = rookies(2019)
df4 = rookies(2018)
df5 = rookies(2017)
df6 = rookies(2016)

In [5]:
df_final = pd.concat([df1, df2, df3, df4, df5, df6])
df_final = df_final[(df_final['RPos'] == 'RB') | (df_final['RPos'] == 'WR') | (df_final['RPos'] == 'TE')]

# Takes total number of Stat, and divides by total games to account for difference between 16/17 game seasons.
df_final['Y/G * 17'] = (df_final['Y/G'] * 17)
df_final['Tgt/G * 17'] = ((df_final['Tgt'] / df_final['G']) * 17)
df_final['Rec/G * 17'] = ((df_final['Rec'] / df_final['G']) * 17)
df_final['TD/G * 17'] = ((df_final['TD'] / df_final['G']) * 17)
df_final

,Player,Tm,Age,G,GS,Tgt,Rec,Ctch%,Yds,Y/R,...,Fmb,Player-additional,Rnd,Pick,RPos,RookieYear,Y/G * 17,Tgt/G * 17,Rec/G * 17,TD/G * 17
7,Jaylen Waddle,MIA,23,16,16,140,104,74.3%,1015,9.8,...,2,WaddJa00,1.0,6.0,WR,2021.0,1077.8,148.750000,110.500000,6.375
15,Amon-Ra St. Brown,DET,22,17,9,119,90,75.6%,912,10.1,...,0,StxxAm00,4.0,112.0,WR,2021.0,911.2,119.000000,90.000000,5.000
19,Ja'Marr Chase*,CIN,21,17,17,128,81,63.3%,1455,18.0,...,2,ChasJa00,1.0,5.0,WR,2021.0,1455.2,128.000000,81.000000,13.000
30,Najee Harris*,PIT,23,17,17,94,74,78.7%,467,6.3,...,0,HarrNa00,1.0,24.0,RB,2021.0,467.5,94.000000,74.000000,3.000
40,Kyle Pitts*,ATL,21,17,15,110,68,61.8%,1026,15.1,...,0,PittKy00,1.0,4.0,TE,2021.0,1026.8,110.000000,68.000000,1.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,D.J. Tialavea,ATL,25,2,0,1,1,100.0%,1,1.0,...,0,TialD.00,8.0,260.0,TE,2016.0,8.5,8.500000,8.500000,8.500
461,Laquon Treadwell,MIN,21,9,1,3,1,33.3%,15,15.0,...,0,TreaLa00,1.0,23.0,WR,2016.0,28.9,5.666667,1.888889,0.000
464,Terrell Watson,PHI,23,1,0,1,1,100.0%,5,5.0,...,0,WatsTe00,8.0,260.0,RB,2016.0,85.0,17.000000,17.000000,0.000
467,Jonathan Williams,BUF,22,11,0,2,1,50.0%,0,0.0,...,2,WillJo07,5.0,156.0,RB,2016.0,0.0,3.090909,1.545455,0.000
469,Shane Wynn,JAX,24,5,0,3,1,33.3%,19,19.0,...,0,WynnSh00,8.0,260.0,WR,2016.0,64.6,10.200000,3.400000,0.000

In [6]:
round(df_final.groupby(['Rnd', 'RPos'])[['G', 'GS', 'Tgt', 'Rec', 'Yds', 'TD', 'Tgt/G * 17', 'Rec/G * 17', 'Y/G * 17', 'TD/G * 17']].mean(),0)

             G    GS   Tgt   Rec    Yds   TD  Tgt/G * 17  Rec/G * 17  \
Rnd RPos
1.0 RB    14.0  12.0  58.0  43.0  344.0  2.0        65.0        48.0
    TE    15.0   9.0  67.0  39.0  523.0  3.0        77.0        45.0
    WR    12.0   9.0  73.0  44.0  595.0  3.0        96.0        57.0
2.0 RB    13.0   5.0  30.0  25.0  204.0  1.0        41.0        32.0
    TE    15.0   7.0  39.0  28.0  274.0  3.0        43.0        30.0
    WR    14.0   7.0  62.0  38.0  505.0  4.0        75.0        46.0
3.0 RB    12.0   4.0  26.0  21.0  174.0  1.0        34.0        26.0
    TE    11.0   4.0  18.0  11.0  143.0  1.0        25.0        15.0
    WR    14.0   5.0  39.0  24.0  313.0  2.0        47.0        28.0
4.0 RB    14.0   2.0  28.0  21.0  152.0  1.0        34.0        25.0
    TE    13.0   5.0  21.0  14.0  158.0  1.0        30.0        21.0
    WR    12.0   3.0  28.0  17.0  195.0  1.0        41.0        25.0
5.0 RB    12.0   2.0  18.0  13.0  100.0  0.0        22.0        15.0
    TE    12.0   3.0  18.0  12.0  120.0  1.0        29.0        20.0
    WR    13.0   3.0  40.0  24.0  296.0  2.0        47.0        28.0
6.0 RB    13.0   1.0  14.0  12.0   89.0  1.0        18.0        14.0
    TE    13.0   4.0  16.0  12.0  107.0  1.0        24.0        17.0
    WR    11.0   2.0  17.0  10.0  127.0  0.0        28.0        16.0
7.0 RB     9.0   1.0   7.0   5.0   39.0  0.0        15.0        11.0
    TE     7.0   2.0  10.0   8.0   76.0  0.0        21.0        14.0
    WR     9.0   1.0  16.0  10.0   99.0  1.0        33.0        19.0
8.0 RB     9.0   1.0  10.0   7.0   57.0  0.0        18.0        14.0
    TE     9.0   2.0   7.0   4.0   49.0  0.0        14.0         9.0
    WR     8.0   1.0  14.0   8.0  106.0  1.0        28.0        17.0

          Y/G * 17  TD/G * 17
Rnd RPos
1.0 RB       388.0        2.0
    TE       590.0        4.0
    WR       754.0        4.0
2.0 RB       266.0        1.0
    TE       301.0        3.0
    WR       607.0        4.0
3.0 RB       232.0        1.0
    TE       179.0        1.0
    WR       373.0        2.0
4.0 RB       179.0        1.0
    TE       238.0        2.0
    WR       280.0        2.0
5.0 RB       122.0        1.0
    TE       195.0        1.0
    WR       351.0        3.0
6.0 RB       116.0        1.0
    TE       159.0        1.0
    WR       214.0        1.0
7.0 RB        79.0        0.0
    TE       159.0        0.0
    WR       192.0        2.0
8.0 RB        98.0        0.0
    TE       101.0        1.0
    WR       215.0        1.0

In [7]:
rookie_stats = pd.DataFrame(round(df_final.groupby(['Rnd', 'RPos'])[['G', 'GS', 'Tgt', 'Rec', 'Yds', 'TD',
                                                                     'Tgt/G * 17', 'Rec/G * 17', 'Y/G * 17', 'TD/G * 17']].mean(),0))
rookie_stats.to_csv('../data/rookie_stats.csv')